# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'sa-ios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sa-ios
  pod 'Alamofire', '~> 4.5'
  pod 'AlamofireObjectMapper', '~> 4.0'
  pod 'AlamofireNetworkActivityIndicator', '~> 2.2'
  pod 'GoogleAnalytics', '~> 3.17.0'
  pod 'OneSignal', '>= 2.5.2', '< 3.0'
  pod 'Rollbar', '~> 0.2.0'
end

target 'sa-ios-class-today' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sa-ios
  pod 'Alamofire', '~> 4.5'
  pod 'AlamofireObjectMapper', '~> 4.0'
  pod 'GoogleAnalytics', '~> 3.17.0'
end
