# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'sa-ios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sa-ios
  pod 'GoogleAnalytics', '~> 3.17.0'
  pod 'Alamofire', '~> 4.4'
  pod 'AlamofireObjectMapper', '~> 4.0'
  pod 'AlamofireNetworkActivityIndicator', '~> 2.0'
  pod 'Sentry', :git => 'https://github.com/getsentry/sentry-swift.git', :tag => '2.1.9'

end
